### ISSUE TITLE
here-doc shell scripts break syntax highlighting

### ISSUE THREAD

**Issue by ndimiduk** [syohex/emacs-terraform-mode#11]
Using 0.4. I have a `user_data` section in an AWS resource, which uses the here-doc syntax. The shell script contains the character sequence `/*` as part of a shell command. This is interpreted as begin multiline quote and break highlighting for the remainder of the file.

**Comment by syohex** [comment]
Sorry here document is not supported yet. I'll try to implement this weekend.

**Comment by syohex** [comment]
Sorry very too late reply. I'm implementation here-doc highlighting at https://github.com/syohex/emacs-hcl-mode/pull/1 now. Could you show me sample code of this issue for writing regression test ?

**Comment by ndimiduk** [comment]
Something like this should demonstrate

```
user_data = <<EOF
#!/usr/bin/env bash
rsync -aHv foo:bar/* ./baz/
EOF
```

**Comment by syohex** [comment]
Thanks for information.

**Comment by syohex** [comment]
I have merged initial highlighting here document implementation. Please upgrade `hcl-mode` version and retry. And please report me if you have any issues. Thanks for reporting issue.

#### Original

![orig](https://cloud.githubusercontent.com/assets/554281/14815349/d2fd3698-0be5-11e6-93b3-7bd7cf457a6c.png)

#### Fixed version
![fixed](https://cloud.githubusercontent.com/assets/554281/14815409/3597da92-0be6-11e6-99b4-106575aa8954.png)

**Comment by ndimiduk** [comment]
That looks right, I'll take it for a spin. Thanks a lot for the quick fix!
