### ISSUE TITLE
Here Documents break syntax highlighting on edit

### ISSUE THREAD

**Issue by k2t0f12d** [syohex/emacs-terraform-mode#14]
Highlighting is normal when you open a .tf, but any editing that triggers syntax evaluation breaks highlighting from the start of the here document to the end of the file.

**Comment by syohex** [comment]
I confirmed it. I need to improve it. However it is difficult to implement :-(

**Comment by kahing** [comment]
Found a workaround, if I add
```
# <<EOF
```
after the stanza with here document, subsequent highlighting/indentation works again (until there's another here document)

**Comment by hartzell** [comment]
terraform-mode 20160823.31
 hcl-mode 20160502.1700
emacs 24.5.1
Mac OS X 10.10.5

---

I seem to have the opposite problem, when I open a terraform configuration file with a heredoc (such as [this example from the terraform source](https://github.com/hashicorp/terraform/blob/master/examples/aws-s3-cross-account-access/main.tf)) the highlighting that comes after the closing occurence of the heredoc marker (e.g. `POLICY`, in that example) is messed up.  If I make an edit (my test case is adding a space character after the heredoc marker) then things are hightlighted correctly.

I've been poking around a bit and have a couple of questions:

You're using this regexp:

```
 "<<[~-]?\\(?:\\([a-zA-Z0-9_]+\\)\\|\"\\([^\"]+\\)\"\\|'\\([^']+\\)'\\)"
```

but HCL here docs must either be `<<FOO` or `<<-FOO` ([here is the code that does the scanning](https://github.com/hashicorp/hcl/blob/master/hcl/scanner/scanner.go#L385).  [Here is the PR that added support for indentation](https://github.com/hashicorp/hcl/pull/91) (allowing `<<-FOO`) (it discussed quoted heredoc markers but rejected the idea).  I can't find any mention of leading the symbol off with a tilde.

I **think** that this means that you could get away with a simpler regexp:

    "<<-?\\([a-zA-Z0-9_]+\\)"

I also think, based on [how the scanner searches for the end of the heredoc](https://github.com/hashicorp/hcl/blob/master/hcl/scanner/scanner.go#L447) that the end-re should match the heredoc-marker followed by the end of the line, not followed by a non-word character

    (let ((end-re (concat "^\\(" heredoc-marker "\\)$")))

**But** having poked around, any/all of those changes don't fix the problem.

**Comment by syohex** [comment]
I have re-written here document highlighting implementation. Could you upgrade hcl-mode and try again ?

**Comment by syohex** [comment]
Thanks

**Comment by joeheyming** [comment]
For some reason here docs look weird for me
![image](https://user-images.githubusercontent.com/1858116/43801986-66b087fc-9a49-11e8-9be6-a6eff03b2495.png)

the closing EOF is not working

Any tips?

**Comment by joeheyming** [comment]
I confirmed that if I add a newline between > and EOF, the parsing works
