### ISSUE TITLE
terraform-indent-level is not respected

### ISSUE THREAD

**Issue by mrwacky42** [syohex/emacs-terraform-mode#7]
If I `(setq terraform-indent-level 4)`, it is not respected, because `indent-line-function` is still bound to `hcl-indent-line`

```
indent-line-function is a variable defined in ‘indent.el’.
Its value is ‘hcl-indent-line’
Local in buffer example.tf; global value is indent-relative
```

For now, I'm just setting `hcl-indent-level` to the desired value to work around the issue.

**Comment by syohex** [comment]
Thanks for reporting issue. I have merged #8. Please check latest version.
